Hw02 express
IamGalexing/nodejs-rest-api pull request #1
Opened 2021-07-03 07:28 UTC by IamGalexing

2021-07-03 22:12 UTC, Danil44 requested changes

2021-07-03 22:12 UTC, Danil44 commented on model/index.js
> +    if (contacts.length === filtered.length) return false
Ліпше створити змінну з назвою isContactExist та використати find замість filter

2021-07-03 22:12 UTC, Danil44 commented on model/index.js
> +    return true
навіщо повертати true чи false?

2021-07-03 22:12 UTC, Danil44 commented on model/index.js
> +    const toUpdate = await contacts.find(
навіщо тут await? find це асинхронна функція?

2021-07-04 08:07 UTC, IamGalexing commented on model/index.js
> +    const toUpdate = await contacts.find(
виправив. Використав await через contacts тут, щоб база якщо на серверi, то все точно пройшло правильно.
А взагалi тут путаэ навiщо взагалi в цих функцiях в ДЗ вони всi написанi через async.
Await цей видалив.

2021-07-04 08:07 UTC, IamGalexing commented on model/index.js
> +    return true
функцiя Delete нам нiякi контакти не повертаэ, тому щоб проконтролювати рeзультат повертаю буль, щоб в з функцii роутера повернути вiдповiдний статyc.

2021-07-04 08:10 UTC, IamGalexing commented on model/index.js
> +    if (contacts.length === filtered.length) return false
переробив, вирiщив, що в такому випадку краще буде вже findIndex нiж find, бо можемо зразу результат використати для splice, щоб видалити контакт.

2021-07-05 10:34 UTC, Danil44 commented on model/index.js
> +    const toUpdate = await contacts.find(
Через async тому що це один з засобів зробити функцію асинхронною. То необов'язково означає, що має бути всередині await

2021-07-05 10:34 UTC, Danil44 approved these changes

2021-07-05 17:41 UTC, merged